import pandas as pd
import os

def apply_manual_translation():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)
    
    # 5 dòng gốc đã failed harsh sweeper
    df_failed = pd.read_csv('../../data/isolated_proofs/harsh_failed_rows.csv')
    
    # Text mà AI (chính tôi) đã vắt óc dịch lại mượt mà, đậm chất thời trang và dọn sạch các từ lặp/AI cliches
    fixed_outputs = {
        1066: "Hãy bắt đầu bằng cách phát huy thế mạnh của bạn. Một thân hình cao, mảnh khảnh có thể diện rất đẹp nhiều phom dáng khác nhau, từ quần ống rộng tạo độ rủ thanh lịch đến váy midi hoặc maxi giúp tôn lên chiều cao. Yếu tố cân bằng đóng vai trò rất quan trọng, vì vậy bạn nên chú ý đến tỷ lệ bằng cách kết hợp đồ form rộng với trang phục ôm sát hơn. Ví dụ, hãy mặc một chiếc áo voan bồng bềnh cùng quần ống côn, hoặc khoác áo blazer cứng cáp bên ngoài quần ống rộng thoải mái. Sự hài hòa về mặt thị giác này sẽ đảm bảo trang phục làm nổi bật dáng vóc tự nhiên của bạn thay vì 'nuốt chửng' nó.\nKhi mua sắm theo hướng bền vững, hãy ưu tiên các phom dáng cổ điển và chất liệu cao cấp như cotton hữu cơ, linen hoặc len có nguồn gốc minh bạch. Áo blazer dáng dài, jumpsuit may đo tinh xảo và váy midi trung tính không bao giờ lỗi mốt chính là những khoản đầu tư xứng đáng, giúp bạn mặc đẹp suốt nhiều năm. Nếu thỉnh thoảng bạn muốn tìm những món đồ nổi bật (như họa tiết táo bạo hay đường cắt độc đáo), hãy thử ghé các cửa hàng đồ cũ hoặc đồ vintage để giảm thiểu tác động đến môi trường. Mua đồ secondhand cũng mang đến cơ hội tuyệt vời để săn những món đồ độc lạ tôn dáng mà không cần phải thỏa hiệp với thời trang nhanh.\nCách tiếp cận linh hoạt và có ý thức đối với sự vừa vặn là điều cốt lõi. Ngay cả một món đồ có phom dáng hoàn hảo cũng đôi khi cần được chỉnh sửa đôi chút cho vừa vặn với chiều dài tay hay chân của bạn. Hãy chú ý đến cấu trúc của trang phục: những bộ quần áo được may đo cẩn thận với đường may chắc chắn và khuy cài chất lượng sẽ đồng hành cùng bạn rất lâu. Bằng cách lựa chọn phom dáng khéo léo để tôn lên vóc dáng cao ráo, ưu tiên chất liệu bền vững và chịu khó chỉnh sửa cho thật vừa vặn, bạn sẽ xây dựng được một tủ đồ bền bỉ, vừa tôn vinh cơ thể vừa thân thiện với Trái đất.",
        
        1194: "Hiện nay có rất nhiều lựa chọn bền vững và không gây hại cho động vật, vừa đáp ứng được tiêu chuẩn về phúc lợi động vật lại vừa đảm bảo độ bền và tính thời trang.\nĐể bắt đầu, bạn có thể tìm hiểu các chất liệu có nguồn gốc thực vật như cotton hữu cơ, vải lanh (linen) và vải gai dầu (hemp). Những chất liệu này đã được sử dụng từ hàng thế kỷ trước nhờ độ thoáng khí tự nhiên và sự bền bỉ. Mặc dù chúng có thể không giữ ấm y hệt như len, nhưng nếu được dệt với mật độ cao và pha trộn chất lượng, chúng vẫn có thể mang lại sự ấm áp, giữ form tốt và dùng được rất lâu, đặc biệt là khi bạn áp dụng phong cách phối đồ nhiều lớp (layering).\nĐối với áo khoác ngoài hoặc giày dép – những món đồ thường dùng da thật – hãy cân nhắc các vật liệu thay thế sáng tạo như da bần (cork), sợi lá dứa (Piñatex), da nấm hoặc da táo. Các vật liệu sinh học này thường có bề mặt và kết cấu tương tự da thật nhưng để lại lượng phát thải môi trường thấp hơn hẳn và dĩ nhiên là hoàn toàn không làm hại đến động vật. Tương tự, các vật liệu tổng hợp tái chế cũng có thể mô phỏng một số đặc tính của len hoặc da, dù vậy bạn vẫn nên kiểm tra kỹ xem quy trình sản xuất của chúng có thực sự thân thiện với môi trường hay không.\nKhi lựa chọn những loại vải nhân đạo này, hãy chú ý đến các chứng nhận uy tín hoặc thông tin sản xuất minh bạch. Các nhãn mác như GOTS (Tiêu chuẩn Dệt may Hữu cơ Toàn cầu) hoặc các tổ chức như Fair Wear Foundation là minh chứng cho việc sản phẩm đáp ứng cả tiêu chuẩn về xã hội lẫn môi trường. Ngoài ra, hãy tìm hiểu cách bảo quản chúng; một số chất liệu sẽ cần được giặt giũ nhẹ nhàng hơn để kéo dài tuổi thọ.\nTheo đuổi thời trang nhân đạo là một hành trình rất ý nghĩa. Dù bạn đang trải nghiệm quần jeans làm từ cotton hữu cơ, một đôi boots da thuần chay hay chiếc áo len pha sợi gai dầu, thì việc nghiên cứu kỹ lưỡng và mua sắm có ý thức sẽ giúp bạn tìm ra những lựa chọn vừa phù hợp với giá trị sống của bản thân, vừa không phải đánh đổi độ bền, phong cách hay tính linh hoạt vượt thời gian.",
        
        1252: "Một bảng màu được lựa chọn khéo léo sẽ giúp việc phối đồ trở nên dễ dàng và gắn kết hơn rất nhiều, bất kể bạn sở hữu vóc dáng hay phong cách cá nhân nào.\nHãy bắt đầu bằng cách quan sát sắc tố tự nhiên của bạn – bao gồm màu da, màu mắt và màu tóc – để tìm ra những tone màu tôn dáng nhất. Tông da ấm thường cực kỳ ăn ý với các màu hệ đất như nâu đậm, xanh olive và nâu xám ấm. Trong khi đó, tông da lạnh sẽ tỏa sáng khi đi cùng các gam màu ngọc quý như xanh sapphire, xanh ngọc lục bảo và các sắc đỏ berry. Các màu trung tính như đen, trắng, xám, be và xanh navy thì lại vô cùng dễ tính, phù hợp với hầu hết mọi nước da và đóng vai trò làm màu nền hoàn hảo cho bất kỳ tủ đồ nào.\nXét về vóc dáng, màu sắc có khả năng tôn lên hoặc che đi các vùng cơ thể một cách đầy tính chiến lược. Các gam màu tối thường tạo hiệu ứng thu gọn, nên việc diện đồ tối màu ở những điểm bạn không muốn thu hút sự chú ý sẽ là một mẹo rất hay. Ngược lại, những màu sắc tươi sáng sẽ bắt sáng và tạo điểm nhấn. Ví dụ, nếu bạn có vóc dáng quả lê, hãy thử phối một chiếc áo sáng màu cùng quần/váy tối màu để cân bằng lại tỷ lệ cơ thể. Nếu bạn muốn trông cao ráo và thanh mảnh hơn, phong cách phối đồ monochrome (đơn sắc) với các sắc độ đậm nhạt khác nhau sẽ tạo ra một tổng thể xuyên suốt từ trên xuống dưới. Bạn cũng có thể thử sức với phong cách layering (phối lớp) bằng cách tạo điểm nhấn màu sắc qua phụ kiện – chẳng hạn như một chiếc khăn quàng sặc sỡ hay chiếc thắt lưng bản to – trong khi vẫn giữ các món đồ chính ở tone màu nhã nhặn.\nViệc giới hạn dải màu là bí quyết để tủ quần áo của bạn không bị quá tải. Hãy chọn ra khoảng hai đến ba màu trung tính chủ đạo, kèm theo hai hoặc ba màu nhấn. Sự tinh gọn này cho phép bạn mix & match các món đồ với nhau cực kỳ dễ dàng. Ví dụ, nếu bạn chốt màu trắng, xanh navy và xám làm màu cốt lõi, bạn hoàn toàn có thể điểm xuyết thêm màu vàng mù tạt hoặc xanh mòng két để set đồ thêm phần thú vị. Mỗi món đồ mới bạn rinh về nên phối được với ít nhất hai hoặc ba món đồ sẵn có; điều này sẽ đảm bảo tính linh hoạt tối đa.\nViệc xây dựng một bảng màu gắn kết thực chất là sự cân bằng hoàn hảo giữa dấu ấn cá nhân và tính ứng dụng. Đừng ngại thử nghiệm các cách kết hợp mới lạ, dù là qua cách phối lớp hay nhấn nhá phụ kiện, để xem điều gì làm bạn cảm thấy tự tin nhất. Bằng cách lấy sắc tố da làm hệ quy chiếu, dùng màu sắc như một vũ khí để cân đối vóc dáng, và giữ bảng màu gọn trong một nhóm các gam màu hài hòa, bạn sẽ tạo dựng được một tủ đồ bền vững, dễ phối và không bao giờ lỗi mốt.",
        
        3633: "Những đôi boots Chelsea và boots cổ ngắn (ankle boots) đơn giản với phần gót cao vừa phải là những thiết kế luôn giữ được sức hút vượt thời gian. Hãy ưu tiên chất liệu da thật hoặc da lộn (suede) với các gam màu kinh điển như đen hoặc nâu để dễ dàng phối với nhiều trang phục nhất. Các thiết kế tối giản – không lạm dụng khóa cài, dây kéo hay chi tiết trang trí rườm rà – sẽ hòa hợp vô cùng tự nhiên với mọi set đồ của bạn.\nNếu bạn cần một lựa chọn cao cổ hơn, boots cưỡi ngựa cao ngang gối (knee-high riding boots) cũng là một items mang đậm chất cổ điển, đặc biệt phù hợp trong thời tiết se lạnh. Hãy lưu ý chọn những đôi boots có phần đế thật chắc chắn (bằng cao su hoặc da) và được gia cố kỹ ở các điểm chịu lực. Mũi giày dáng hơi nhọn hoặc dáng quả hạnh nhân (almond toe) luôn mang đến cảm giác thanh lịch truyền thống, trong khi những phom dáng quá phá cách thường chỉ mang tính xu hướng nhất thời. Bằng cách chọn một đôi boots có phom dáng thanh thoát, cao vừa phải, bạn sẽ sở hữu một món phụ kiện đa năng, dễ dàng ứng dụng qua nhiều mùa và nhiều hoàn cảnh khác nhau.",
        
        7785: "Thuê trang phục là một cách tuyệt vời để giảm thiểu rác thải sản xuất bằng cách xoay vòng vòng đời của một món đồ, đặc biệt là với những bộ cánh mà bạn chỉ mặc một, hai lần. Tuy nhiên, bạn cũng cần cân nhắc đến lượng khí thải carbon phát sinh trong quá trình vận chuyển. Để tối ưu hóa, hãy ưu tiên các dịch vụ cho thuê có điểm trả đồ gần nhà hoặc có chính sách giao nhận hàng loạt.\nBên cạnh đó, hãy tìm hiểu về quy trình giặt khô của họ; hiện nay đã có một số công ty cho thuê sử dụng dung môi làm sạch thân thiện với môi trường. Quan trọng nhất, hãy chỉ thuê trang phục khi bạn thực sự cần cho một sự kiện đặc biệt, thay vì thuê chỉ vì sở thích bốc đồng. Đối với những món đồ mà bạn xác định sẽ mặc thường xuyên, việc đầu tư mua hẳn một sản phẩm mang tính bền vững sẽ mang lại hiệu quả cao hơn về lâu dài.\nHoạt động thuê quần áo là một giải pháp bảo vệ môi trường rất hiệu quả đối với những nhu cầu mặc đồ ít thường xuyên. Thế nhưng, bạn vẫn nên cân đo đong đếm giữa quãng đường vận chuyển và các phương pháp làm sạch đi kèm để đảm bảo rằng mình đang thực sự mang lại giá trị tích cực cho môi trường."
    }
    
    # Cập nhật kết quả vào dataframe
    for idx, row in df_failed.iterrows():
        df_failed.at[idx, 'translated_output'] = fixed_outputs[row['ID']]
        
    df_failed.to_csv('../../data/isolated_proofs/fixed_5_rows.csv', index=False)
    
    # Đọc lại 1483 dòng siêu sạch
    clean_df = pd.read_csv('../../data/isolated_proofs/ultimate_clean_1500.csv')
    
    # Hợp nhất
    final_df = pd.concat([clean_df, df_failed.drop(columns=['fail_reason', 'harsh_fail_reason'])], ignore_index=True)
    final_df.to_csv('../../data/isolated_proofs/distilled_1488_perfect.csv', index=False)
    print("Successfully manual translated 5 rows and generated final 1488 perfect dataset.")

if __name__ == '__main__':
    apply_manual_translation()
